version: '3.8'

services:
  # Nacos服务注册中心
  nacos:
    image: nacos/nacos-server:v2.2.3
    container_name: coffee-nacos
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_USER=nacos
      - MYSQL_SERVICE_PASSWORD=nacos
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
      - NACOS_AUTH_IDENTITY_KEY=serverIdentity
      - NACOS_AUTH_IDENTITY_VALUE=security
    volumes:
      - ./logs/nacos:/home/nacos/logs
    depends_on:
      - mysql
    networks:
      - coffee-network

  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: coffee-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=nacos
      - MYSQL_USER=nacos
      - MYSQL_PASSWORD=nacos
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database-scripts:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - coffee-network

  # Redis缓存
  redis:
    image: redis:7.0-alpine
    container_name: coffee-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass 123456
    networks:
      - coffee-network

  # RabbitMQ消息队列
  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: coffee-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123456
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - coffee-network

  # API网关
  gateway:
    build:
      context: ./coffee-gateway
      dockerfile: Dockerfile
    container_name: coffee-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NACOS_SERVER_ADDR=nacos:8848
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - nacos
      - mysql
      - redis
    networks:
      - coffee-network

  # 用户服务
  user-service:
    build:
      context: ./coffee-user-service
      dockerfile: Dockerfile
    container_name: coffee-user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NACOS_SERVER_ADDR=nacos:8848
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - nacos
      - mysql
      - redis
    networks:
      - coffee-network

  # 商品服务
  product-service:
    build:
      context: ./coffee-product-service
      dockerfile: Dockerfile
    container_name: coffee-product-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NACOS_SERVER_ADDR=nacos:8848
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - nacos
      - mysql
      - redis
    networks:
      - coffee-network

  # 订单服务
  order-service:
    build:
      context: ./coffee-order-service
      dockerfile: Dockerfile
    container_name: coffee-order-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NACOS_SERVER_ADDR=nacos:8848
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - nacos
      - mysql
      - redis
      - rabbitmq
    networks:
      - coffee-network

  # 优惠券服务
  coupon-service:
    build:
      context: ./coffee-coupon-service
      dockerfile: Dockerfile
    container_name: coffee-coupon-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NACOS_SERVER_ADDR=nacos:8848
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - nacos
      - mysql
      - redis
      - rabbitmq
    networks:
      - coffee-network

  # 购物车服务
  cart-service:
    build:
      context: ./coffee-cart-service
      dockerfile: Dockerfile
    container_name: coffee-cart-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NACOS_SERVER_ADDR=nacos:8848
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - nacos
      - mysql
      - redis
    networks:
      - coffee-network

  # AI服务
  ai-service:
    build:
      context: ./coffee-ai-service
      dockerfile: Dockerfile
    container_name: coffee-ai-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NACOS_SERVER_ADDR=nacos:8848
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - nacos
      - mysql
      - redis
    networks:
      - coffee-network

  # 统计服务
  statistics-service:
    build:
      context: ./coffee-statistics-service
      dockerfile: Dockerfile
    container_name: coffee-statistics-service
    ports:
      - "8087:8087"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - NACOS_SERVER_ADDR=nacos:8848
      - MYSQL_HOST=mysql
      - REDIS_HOST=redis
    depends_on:
      - nacos
      - mysql
      - redis
    networks:
      - coffee-network

volumes:
  mysql-data:
  redis-data:
  rabbitmq-data:

networks:
  coffee-network:
    driver: bridge
